### ISSUE TITLE
Git version tag(s) for Packagist

### ISSUE THREAD

**Issue by danmichaelo** [pear/Validate_ISPN#3]
Hi,

Packagist reads version numbers from git tags, but there's no [git tags](https://github.com/pear/Validate_ISPN/tags) in this repo, so currently you can only install the `dev-master` version. Could you do `git tag 0.6.1` (and I think we also need a new release since the composer file has been added after 0.6.1)

**Comment by danmichaelo** [comment]
@CloCkWeRX , think you could have a look at this?

**Comment by ashnazg** [comment]
v0.6.1 and new v.0.7.0 are now tagged
